import { ApiProperty } from "@nestjs/swagger";
import { BaseEntity } from "src/common/entities/base.entity";
import { City } from "src/modules/city/entities/city.entity";
import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Adress extends BaseEntity{
    @ApiProperty({
        title: "id",
        description: "autogenerated id"
    })
    @PrimaryGeneratedColumn('uuid')
    id: string

    @ApiProperty({
        title: 'street'
    })
    @Column('varchar', {nullable: false})
    street: string

    @ApiProperty({
        title: 'number'
    })
    @Column('varchar', {nullable: false})
    number: string
   
    @ApiProperty({
        title: 'number'
    })
    @Column('varchar', {nullable: false})
    note: string
    
    
    @ApiProperty({
        title: 'postalCode'
    })
    @Column('varchar', {nullable: false})
    postalCode: string


    @ApiProperty({
        title: 'city'
    })
    @ManyToOne(() => City, (city) => city.adresses)
    city: City
}
