import { ApiProperty } from "@nestjs/swagger";
import { BaseEntity } from "src/common/entities/base.entity";
import { City } from "src/modules/city/entities/city.entity";
import { Instalation } from "src/modules/instalations/entities/instalation.entity";
import { Column, DeepPartial, Entity, ManyToOne, OneToMany, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Adress extends BaseEntity{
    
    @ApiProperty({
        title: "id",
        description: "autogenerated id"
    })
    @PrimaryGeneratedColumn('uuid')
    id: string

    @ApiProperty({
        title: 'street'
    })
    @Column('varchar', {nullable: false})
    street: string

    @ApiProperty({
        title: 'number'
    })
    @Column('varchar', {nullable: false})
    number: string
   
    @ApiProperty({
        title: 'number'
    })
    @Column('varchar', {nullable: false})
    note: string
    
    
    @ApiProperty({
        title: 'postalCode'
    })
    @Column('varchar', {nullable: false})
    postalCode: string

    @ApiProperty({
        title: 'startDate',
        description: "The day when start the instalation"
    })
    @OneToMany(() => Instalation, (instalation) => instalation.adress, {nullable: true})
    instalations: Instalation[]

    @ApiProperty({
        title: 'city'
    })
    @ManyToOne(() => City, (city) => city.adresses)
    city: City

    constructor(partial: DeepPartial<Adress>) {
        super()
        Object.assign(this, partial)
    }

}
