import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";
import { BaseEntity } from "../../../common/entities/base.entity";
import { ApiProperty } from "@nestjs/swagger";

@Entity()
export class BlogPostTemplate extends BaseEntity {

    @ApiProperty({
        title: 'id',
        description: 'autogenerated uuid',
        type: 'string'
    })
    @PrimaryGeneratedColumn('uuid')
    id: string

    @ApiProperty({
        title: 'name',
        description: "tamplate's name",
        type: 'string'
    })
    @Column('varchar', {nullable: false})
    name: string

    @ApiProperty({
        title: 'id',
        description: 'autogenerated uuid',
        type: 'string'
    })
    @Column('integer',{name: 'number_of_content_blocks', nullable: false})
    numberOfContentBlocks: number


}