name: render-deploy-backend

on:
  push:
    branches: main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ##Upload to docker hub

      - name: Set up docker build
        uses: docker/setup-buildx-action@v3

      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      -
        name: Build and push
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          push: true
          tags: oriel/gf-web-service:latest

      ##Deploy to render

      - name: Deploy to render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: truecd
